name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instal Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
K          echo "$HOME/.b
